#!/bin/bash

# Useful
# MDP options: https://manual.gromacs.org/2023.2/user-guide/mdp-options.html
# File formats: https://manual.gromacs.org/2023.2/reference-manual/file-formats.html

# Details
# Force field setup: https://manual.gromacs.org/2023.2/user-guide/force-fields.html#charmm


# Advanced argument parsing
while getopts "i:h" opt; do
    case ${opt} in
        i ) input=${OPTARG} ;;
        h ) echo "Usage: prepareMD -i inputname"; exit 0 ;;
        \? ) echo "Invalid option: $OPTARG" 1>&2; exit 1 ;;
    esac
done

checkDependency() {
    command -v $1 >/dev/null 2>&1 || { echo >&2 "I require $1 but it's not installed.  Aborting."; exit 1; }
}

checkFile() {
    [ -f $1 ] || { echo >&2 "Error: File $1 is not found.  Aborting."; exit 1; }
}

checkFiles() {
    for file in "$@"; do
        checkFile $file
    done
}

createMDP () {
cat > $1 << EOF
; Run parameters
integrator              = md 
dt                      = 0.002     
nsteps                  = 500000

; Output control
nstxout-compressed      = 5000   ; coordinates
nstvout                 = 5000   ; velocities
nstenergy               = 5000   ; energy saving
nstlog                  = 5000   ; log file
nstcalcenergy 		    = 100    ; energie calculation

; Non-bonded parameters
cutoff-scheme           = Verlet 
nstlist                 = 20  
rlist                   = 1.2
vdwtype                 = Cut-off
vdw-modifier            = Force-switch
rvdw-switch             = 1.0
rvdw                    = 1.2

; Electrostatics
coulombtype             = PME       
rcoulomb                = 1.2      
DispCorr                = no

; Temperature coupling
tcoupl                  = V-rescale                 
tc-grps                 = Protein Non-Protein
tau-t                   = 0.1 0.1                   
ref-t                   = 293 293

; Bond constraints
constraints             = h-bonds
constraint-algorithm    = LINCS 

; Center of mass
comm-mode               = Linear
EOF
}

addPositionRestraints () {
    cat >> $1 << EOF
; Position restraints
define                  = -DPOSRES
EOF
}

addPressureCoupling () {
    cat >> $1 << EOF
; Pressure coupling
pcoupl                  = C-rescale
pcoupltype              = isotropic
tau-p                   = 2.0
ref-p                   = 1.0
compressibility         = 4.5e-5
refcoord-scaling        = com
EOF
}

setupSimulationMode () {
    if [ $2 == "start" ]; then
        cat >> $1 << EOF
; Bond constraints
continuation            = no

; Velocity generation
gen-vel                 = yes
gen-temp                = 293
gen-seed                = -1
EOF
    elif [ $2 == "continue" ]; then
        cat >> $1 << EOF
; Bond constraints
continuation            = yes
; Velocity generation
gen-vel                 = no
EOF
    fi
}

convertPDBToGROMACS() {
    gmx pdb2gmx -f "$input.pdb" -o protein_processed.gro -p topol.top -i posre.itp -posrefc 1000 -ff charmm36-jul2022 -water tip3p -ignh -nobackup
    checkFiles protein_processed.gro topol.top posre.itp
}


defineSimulationBox() {
    gmx editconf -f protein_processed.gro -o protein_newbox.gro -c -d 1.5 -bt cubic -nobackup
    checkFiles protein_newbox.gro
}


solvateSystem() {
    gmx solvate -cp protein_newbox.gro -cs spc216.gro -o protein_solv.gro -p topol.top -nobackup
    checkFiles protein_solv.gro
}


addIons() {
    touch ions.mdp
    checkFile ions.mdp

    gmx grompp -f ions.mdp -c protein_solv.gro -o ions.tpr -p topol.top
    checkFile ions.tpr

    gmx genion -s ions.tpr -o solv_ions.gro -p topol.top -pname NA -nname CL -conc 0.15 -neutral -nobackup <<< "SOL"
    checkFile solv_ions.gro
}


energyMinimization() {
    cat > em.mdp << EOF
; Run parameters
integrator      = steep     ; Steepest descent minimization
emtol           = 100.0     ; Tolerance for energy minimization
emstep          = 0.01      ; Minimization step size
nsteps          = 10000     ; Max steps for energy minimization

; Non-bonded parameters
cutoff-scheme   = Verlet    ; Use Verlet list for neighbor search
nstlist         = 10        ; Update neighbor list every step
rlist           = 1.2       ; Cut-off for making neighbor list (short range forces)
ns-type         = grid      ; Grid search for neighbor list
rvdw            = 1.2       ; Cut-off for Van der Waals interactions in nm

; Electrostatics
coulombtype     = PME       ; Particle Mesh Ewald for long-range electrostatics
rcoulomb        = 1.2       ; Cut-off for Coulomb interactions in nm
DispCorr        = no

; Bond constraints
constraints     = h-bonds 
constraint-algorithm = LINCS 
EOF
    checkFile em.mdp

    gmx grompp -f em.mdp -c solv_ions.gro -p topol.top -o em.tpr
    checkFile em.tpr

    gmx mdrun -deffnm em -nb gpu
    checkFiles em.gro em.edr em.trr em.log

    gmx energy -f em.edr -o em_potential.xvg -xvg none -nobackup <<< $'Potential\n0\n'
    checkFile em_potential.xvg
    
}


nvtEquilibration() {
    createMDP nvt.mdp
    addPositionRestraints nvt.mdp
    setupSimulationMode nvt.mdp start
    checkFile nvt.mdp

    gmx grompp -f nvt.mdp -c em.gro -r em.gro -p topol.top -o nvt.tpr
    checkFile nvt.tpr

    gmx mdrun -deffnm nvt -nb gpu
    checkFiles nvt.log nvt.trr nvt.edr nvt.xtc nvt.gro nvt.cpt

    gmx energy -f nvt.edr -o nvt_temperature.xvg -xvg none -nobackup <<< $'Temperature\n0\n'
    checkFile nvt_temperature.xvg
}


nptEquilibration() {
    createMDP npt.mdp
    addPositionRestraints npt.mdp
    addPressureCoupling npt.mdp
    setupSimulationMode npt.mdp continue
    checkFile npt.mdp

    gmx grompp -f npt.mdp -c nvt.gro -t nvt.cpt -r em.gro -p topol.top -o npt.tpr
    checkFile npt.tpr

    gmx mdrun -deffnm npt -nb gpu
    checkFiles npt.log npt.trr npt.edr npt.xtc npt.gro npt.cpt

    gmx energy -f npt.edr -o npt.xvg -xvg none -nobackup <<< $'Pressure\nDensity\nPosition-Rest\nPotential\n0\n'
    checkFile npt.xvg
}


eliminateRestraints() {
    createMDP rst200.mdp
    addPositionRestraints rst200.mdp
    addPressureCoupling rst200.mdp
    setupSimulationMode rst200.mdp continue
    checkFile rst200.mdp

    sed -i 's/1000/200/g' posre.itp 

    gmx grompp -f rst200.mdp -c npt.gro -t npt.cpt -r em.gro -p topol.top -o rst_200.tpr
    checkFile rst_200.tpr

    gmx mdrun -deffnm rst_200 -nb gpu
    checkFiles rst_200.log rst_200.edr rst_200.trr rst_200.xtc rst_200.gro rst_200.cpt

    gmx energy -f rst_200.edr -o rst_200.xvg -xvg none -nobackup <<< $'Pressure\nDensity\nPosition-Rest\nPotential\n0\n'
    checkFile rst_200.xvg


    createMDP rst50.mdp
    addPositionRestraints rst50.mdp
    addPressureCoupling rst50.mdp
    setupSimulationMode rst50.mdp continue
    checkFile rst50.mdp

    sed -i 's/200/50/g' posre.itp 

    gmx grompp -f rst50.mdp -c rst_200.gro -t rst_200.cpt -r em.gro -p topol.top -o rst_50.tpr
    checkFile rst_50.tpr

    gmx mdrun -deffnm rst_50 -nb gpu
    checkFiles rst_50.log rst_50.edr rst_50.trr rst_50.xtc rst_50.gro rst_50.cpt

    gmx energy -f rst_50.edr -o rst_50.xvg -xvg none -nobackup <<< $'Pressure\nDensity\nPosition-Rest\nPotential\n0\n'
    checkFile rst_50.xvg


    createMDP rst10.mdp
    addPositionRestraints rst10.mdp
    addPressureCoupling rst10.mdp
    setupSimulationMode rst10.mdp continue
    checkFile rst10.mdp

    sed -i 's/50/10/g' posre.itp 

    gmx grompp -f rst10.mdp -c rst_50.gro -t rst_50.cpt -r em.gro -p topol.top -o rst_10.tpr
    checkFile rst_10.tpr

    gmx mdrun -deffnm rst_10 -nb gpu
    checkFiles rst_10.log rst_10.edr rst_10.trr rst_10.xtc rst_10.gro rst_10.cpt

    gmx energy -f rst_10.edr -o rst_10.xvg -xvg none -nobackup <<< $'Pressure\nDensity\nPosition-Rest\nPotential\n0\n'
    checkFile rst_10.xvg


    createMDP rst0.mdp
    addPressureCoupling rst0.mdp
    setupSimulationMode rst0.mdp continue
    checkFile rst0.mdp

    gmx grompp -f rst0.mdp -c rst_10.gro -t rst_10.cpt -p topol.top -o rst_0.tpr -maxwarn 1 #Warning with center of mass removal
    checkFile rst_0.tpr

    gmx mdrun -deffnm rst_0 -nb gpu
    checkFiles rst_0.log rst_0.edr rst_0.trr rst_0.xtc rst_0.gro rst_0.cpt

    gmx energy -f rst_0.edr -o rst_0.xvg -xvg none -nobackup <<< $'Pressure\nDensity\n0\n'
    checkFile rst_0.xvg
}

shortFreeMD() {
    createMDP md.mdp
    setupSimulationMode md.mdp continue
    checkFile md.mdp

    gmx grompp -f md.mdp -c rst_0.gro -t rst_0.cpt -p topol.top -o md.tpr  -maxwarn 1 #Warning with center of mass removal
    checkFile md.tpr

    gmx mdrun -deffnm md -nb gpu
    checkFiles md.log md.edr md.trr md.xtc md.gro md.cpt

    gmx energy -f md.edr -o md.xvg -xvg none -nobackup <<< $'Pressure\n0\n'
    checkFile md.xvg
}

checkDependency "gmx"

convertPDBToGROMACS
defineSimulationBox
solvateSystem
addIons
energyMinimization
nvtEquilibration
nptEquilibration
eliminateRestraints
shortFreeMD

echo "MD Preparation completed successfully."
