version: '3.8'
services:
  app:
    build: .
    image: pddb-app
    container_name: pddb-app
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.development

  db:
    image: mongo
    container_name: pddb-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env.mongo
    volumes:
      - mongo:/data/db

volumes:
    mongo:
